name: For pull requests
on:
  pull_request:
    branches: [ master ]

jobs:
  pull_request_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
      - run: |
          npm install
          npm run build
